webapp/user/models.py
"""
Init user models
"""
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from webapp.db import db
from webapp.playlist.models import Playlist


class User(db.Model, UserMixin):
    """
    User model
    """
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password = db.Column(db.String(128), nullable=False)
    role = db.Column(db.String(10), index=True)
    email = db.Column(db.String(50), nullable=False)
    registration_date = db.Column(db.String(20), nullable=False)
    yandex_token = db.Column(db.String(100), nullable=True)
    spotify_token = db.Column(db.String(500), nullable=True)

    def __repr__(self):
        """
        Rerp of a User model
        """
        return f"<User {self.username} id {self.id}>"

    def set_password(self, password):
        """
        Encrypt password
        """
        self.password = generate_password_hash(password)

    def check_password(self, password):
        """
        Check password hash
        """
        return check_password_hash(self.password, password)

    @property
    def is_admin(self):
        """
        Check if user is admin
        """
        return self.role == "admin"

    def count_playlist(self):
        """
        User's playlists counter
        """
        return Playlist.query.filter(Playlist.user == self.id).count()

webapp/user/forms.py
"""
Init user forms
"""
from flask_wtf import FlaskForm
from wtforms import BooleanField, PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from webapp.user.models import User


class LoginForm(FlaskForm):
    """
    Login form
    """
    username = StringField(
        "Имя пользователя",
        validators=[DataRequired()],
        render_kw={"class": "form-control"},
    )
    password = PasswordField(
        "Пароль", validators=[DataRequired()], render_kw={"class": "form-control"}
    )
    remember_me = BooleanField(
        "Запомнить меня", default=True, render_kw={"class": "form-check-input"}
    )
    submit = SubmitField("Отправить", render_kw={"class": "btn btn-primary"})


class RegistrationForm(FlaskForm):
    """
    Registration form
    """
    username = StringField(
        "Имя пользователя",
        validators=[DataRequired()],
        render_kw={"class": "form-control"},
    )
    email = StringField(
        "Электронная почта",
        validators=[DataRequired(), Email()],
        render_kw={"class": "form-control"},
    )
    password = PasswordField(
        "Пароль", validators=[DataRequired()], render_kw={"class": "form-control"}
    )
    password2 = PasswordField(
        "Повторите пароль",
        validators=[DataRequired(), EqualTo("password")],
        render_kw={"class": "form-control"},
    )
    submit = SubmitField("Отправить", render_kw={"class": "btn btn-primary"})

    def validate_username(self, username):
        """
        Validating an username
        """
        users_count = User.query.filter_by(username=username.data).count()
        if users_count > 0:
            raise ValidationError("Пользователь с таким именем уже существует")

    def validate_email(self, email):
        """
        Validating an email
        """
        users_count = User.query.filter_by(email=email.data).count()
        if users_count > 0:
            raise ValidationError("Пользователь с такой почтой уже существует")


class YandexLoginForm(FlaskForm):
    """
    Yandex login form
    """
    email = StringField(
        "Электронная почта",
        validators=[DataRequired(), Email()],
        render_kw={"class": "form-control"},
    )
    password = PasswordField(
        "Пароль", validators=[DataRequired()], render_kw={"class": "form-control"}
    )
    submit = SubmitField("Отправить", render_kw={"class": "btn btn-primary"})

webapp/playlist/views.py
"""
Playlist views
"""
from datetime import datetime
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import login_required

from webapp.db import db
from webapp.playlist.forms import PlaylistLinkForm
from webapp.playlist.models import Playlist, Track
from webapp.spotify.spotify import get_playlist_by_id
from webapp.ya_music.ya_music import get_playlist_ya

blueprint = Blueprint("playlist", __name__, url_prefix="/playlist")


@blueprint.route("/", methods=["GET", "POST"])
@login_required
def search_playlist_by_url():
    """View for search playlist by url

    Returns:
        HTML page with playlist-link form.
    """
    title = "AnySync"
    url_form = PlaylistLinkForm()

    return render_template("playlist/search_playlist_by_url.html", page_title=title, form=url_form)


@blueprint.route("/search-playlist-process", methods=["POST"])
@login_required
def search_playlist_process():
    """
    Search playlist process page, validating the form
    """
    url_form = PlaylistLinkForm()
    if url_form.validate_on_submit():
        if "spotify" in url_form.link.data:
            try:
                new_playlist = get_playlist_by_id(url_form.link.data)
                return redirect(url_for("playlist.playlist", playlist_id=new_playlist.id))
            except Exception:
                flash('Несуществующий плейлист в Spotify')
                return redirect(url_for("playlist.search_playlist_by_url"))
        if "yandex" in url_form.link.data:
            try:
                new_playlist = get_playlist_ya(url_form.link.data)
                return redirect(url_for("playlist.playlist", playlist_id=new_playlist.id))
            except Exception:
                flash('Несуществующий плейлист в Yandex Music')
                return redirect(url_for("playlist.search_playlist_by_url"))

        flash("Неправильная ссылка, попробуйте еще раз")
        return redirect(url_for("playlist.search_playlist_by_url"))

    flash("Ошибка при заполнении формы, попробуйте еще раз")
    return redirect(url_for("playlist.search_playlist_by_url"))


@blueprint.route("/playlists")
@login_required
def all_playlists():
    """View for all playlists

    Returns:
        HTML page with all users playlists.
    """
    title = "Список плейлистов"
    playlists = Playlist.query.all()

    return render_template(
        "playlist/playlists.html", page_title=title, playlists=playlists
    )


@blueprint.route("/playlist/<playlist_id>", methods=["GET", "POST"])
@login_required
def playlist(playlist_id):
    """View for playlist by id

    Returns:
        HTML page with tracks by playlist id.
    """
    title = "Треклист"
    current_playlist = Playlist.query.filter(Playlist.id == playlist_id).first()
    track_list = Track.query.filter(Track.playlist == playlist_id)

    return render_template(
        "playlist/playlist.html",
        page_title=title,
        track_list=track_list,
        current_playlist=current_playlist,
    )


@blueprint.route("/playlist_user/<user_id>", methods=["GET", "POST"])
@login_required
def playlist_user(user_id):
    """View for playlists by user id

    Returns:
        HTML page with playlists by user id
    """
    title = "Мои плейлисты"
    playlists = Playlist.query.filter(Playlist.user == user_id)
    return render_template(
        "playlist/playlist_user.html",
        page_title=title,
        playlists=playlists,
        user_id=user_id,
    )


@blueprint.route("/delete_playlist/<playlist_id>")
@login_required
def delete_playlist(playlist_id):
    """View for deleting playlist from the db

    Args:
        playlist_id: playlist id

    Returns:
        redirect to a user profile page
    """
    playlist_to_delete = Playlist.query.get(int(playlist_id))
    Track.query.filter(Track.playlist == int(playlist_id)).delete()
    db.session.delete(playlist_to_delete)
    db.session.commit()

    return redirect(url_for("user.profile"))


@blueprint.route("/delete_track_from_playlist/<track_id>")
@login_required
def delete_track(track_id):
    """View for deleting playlist from the db

    Args:
        track_id: track_id id

    Returns:
        redirect to the playlist page
    """
    track_to_delete = Track.query.get(int(track_id))
    playlist_id = track_to_delete.playlist
    playlist_to_update = Playlist.query.get(track_to_delete.playlist)
    playlist_to_update.last_update = datetime.today()

    db.session.delete(track_to_delete)
    db.session.commit()

    return redirect(url_for("playlist.playlist", playlist_id=playlist_id))

webapp/user/__init__.py
"""
Init user
"""

webapp/user/views.py
"""
Init user views
"""
from datetime import datetime

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
# from yandex_music import Client

from webapp.db import db
from webapp.playlist.models import Playlist
from webapp.spotify.spotify import spotify_auth, sync_to_spotify
from webapp.user.forms import LoginForm, RegistrationForm, YandexLoginForm
from webapp.user.models import User
from webapp.ya_music.token_ya import yandex_ouath


blueprint = Blueprint("user", __name__, url_prefix="/users")


@blueprint.route("/profile")
@login_required
def profile():
    """
    User profile page
    """
    title = "Мой AnySync"
    playlists = Playlist.query.filter(Playlist.user == current_user.id)
    return render_template("user/my_anysync.html", title=title, playlists=playlists)


@blueprint.route("/startspotoauth")
@login_required
def start_spot_oauth():
    """
    Getting an auth_url then redirect
    """
    auth_manager = spotify_auth()
    auth_url = auth_manager.get_authorize_url()
    print(auth_url)

    return redirect(auth_url)


@blueprint.route("/spotifyoauth")
@login_required
def spotifyoauth():
    """
    Getting spotify auth token
    """
    auth_manager = spotify_auth()
    print(request.args)
    auth_manager.get_access_token(request.args.get("code"))

    return redirect(url_for("user.synchronization", music_service="Spotify"))


@blueprint.route('/yandex-login-process', methods=["POST"])
@login_required
def yandex_login_process():
    """
    Yandex auth process page, validating form
    """
    form = YandexLoginForm()
    flash_message = "Неправильное имя пользователя или пароль"
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        auth_result, flash_message = yandex_ouath(email, password)
        if auth_result:
            flash(flash_message)
            return redirect(url_for("user.synchronization", music_service="Yandex Music"))
    flash(flash_message)

    return redirect(url_for("user.yandexoauth"))


@blueprint.route("/yandexoauth")
@login_required
def yandexoauth():
    """
    Check if the user already have a token, if not redirect to Yandex Auth
    """
    if current_user.yandex_token is None:
        title = 'Яндекс Авторизация'
        form = YandexLoginForm()
        return render_template(
            "user/yandexoauth.html",
            page_title=title,
            form=form,
        )
    return redirect(url_for("user.synchronization", music_service="Yandex Music"))


@blueprint.route("/sync-playlist")
@login_required
def sync_playlist():
    """
    Sync playlist in music service
    """
    playlist_ids = request.values.getlist("playlist")
    music_service = request.values.get("music_service")
    public_playlist = request.values.get("public_playlist") == "True"

    if music_service == "Spotify":
        auth_manager = spotify_auth()
        sync_to_spotify(
            playlist_ids=playlist_ids,
            public_playlist=public_playlist,
            auth_manager=auth_manager,
        )
    elif music_service == "Yandex Music":
        from webapp.tasks import new_playlist
        token = current_user.yandex_token
        # client = Client(token).init()
        new_playlist.delay(playlist_ids=playlist_ids, token=token)
    return redirect(url_for('user.profile'))


@blueprint.route("/synchronization/<music_service>")
@login_required
def synchronization(music_service):
    """
    Synchronization page with playlist checkboxes
    """
    title = "Синхронизация плейлистов"
    playlists = Playlist.query.filter(Playlist.user == current_user.id)

    return render_template(
        "user/synchronization.html",
        title=title,
        playlists=playlists,
        music_service=music_service,
    )


@blueprint.route("/login")
def login():
    """
    Login page
    """
    if current_user.is_authenticated:
        return redirect(url_for("index"))
    title = "Авторизация"
    login_form = LoginForm()

    return render_template("user/login.html", page_title=title, form=login_form)


@blueprint.route("/process-login", methods=["POST"])
def process_login():
    """
    Validatin login form
    """
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("Вы успешно вошли на сайт")
            return redirect(url_for("index"))
    flash("Неправильное имя пользователя или пароль")

    return redirect(url_for("user.login"))


@blueprint.route("/logout")
def logout():
    """
    Logout view
    """
    logout_user()
    flash("Вы успешно разлогинились")

    return redirect(url_for("index"))


@blueprint.route("/register")
def register():
    """
    Registration page
    """
    if current_user.is_authenticated:
        return redirect(url_for("index"))
    title = "Регистрация"
    form = RegistrationForm()

    return render_template("user/registration.html", page_title=title, form=form)


@blueprint.route("/process-reg", methods=["POST"])
def process_reg():
    """
    Validating registration form
    """
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(
            username=form.username.data,
            email=form.email.data,
            role="user",
            registration_date=datetime.today().strftime("%Y-%d-%m %H:%M:%S"),
        )
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash("Вы успешно зарегистрировались!")
        return redirect(url_for("user.login"))

    for field, errors in form.errors.items():
        for error in errors:
            flash(
                f'Ошибка в поле \
                "{getattr(form, field).label.text}": - {error}'
            )
    return redirect(url_for("user.register"))

webapp/templates/user/activate.html
{% extends 'base.html' %}

{% block content %}
<p>Welcome! Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Cheers!</p>
{% endblock %}

webapp/templates/user/login.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-4">
		<h1>{{ page_title }}</h2>
		<form action="{{ url_for('user.process_login') }}" method="post">
			{{ form.hidden_tag() }}
			<div class="form-group">
				{{ form.username.label }}<br>
				{{ form.username() }}
			</div>
			<div class="form-group">
				{{ form.password.label }}<br>
				{{ form.password() }}
			</div>
			<div class="form-group form-check">
				{{ form.remember_me() }}
				{{ form.remember_me.label(class_='form-check-label') }}
			</div>
			{{ form.submit }}
		</form>
	</div>
</div>
{% endblock %}

webapp/templates/user/my_anysync.html
{% extends 'base.html' %}

{% block content %}
<div class="row mt-5 mb-5 text-center">
    <div class="col">
        <h2 class="mb-3">AnySync</h2>
        <a href="{{ url_for('playlist.search_playlist_by_url') }}" type="button" class="btn btn-secondary">Добавить новый плейлист</a>
        <div class="btn-group dropright">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Синхронизация плейлистов
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{{ url_for('user.start_spot_oauth') }}"><i class="fa-brands fa-spotify mr-2"></i>Spotify</a>
                <a class="dropdown-item" href="{{ url_for('user.yandexoauth') }}"><i class="fa-brands fa-yandex pr-2 mr-2"></i>Yandex Music</a>
            </div>
        </div>
    </div>
</div>
<hr>
<h4 class="text-center">Мои плейлисты</h4>
<hr>
<div class="row mt-3">
    {% for playlist in playlists %}
        <div class="col-4 mb-3">
            <div class="card text-center" style="width: 18rem;">
                <img class="card-img-top" src="{{ playlist.img_cover }}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title" id="{{ playlist.id }}">{{ playlist.playlist_name }}</h5>
                    <p class="card-text">Количество треков: {{ playlist.count_tracks() }}</p>
                    <p class="card-text">Создатель плейлиста: <br>{{ playlist.owner_name }}</p>
                    <p class="card-text">Последнее обновление: <br>{{ playlist.last_update }}</p>
                    <div class="row">
                        <div class="col">
                            <a href="{{ url_for('playlist.playlist', playlist_id=playlist.id) }}" class="btn btn-dark">Открыть</a>
                        </div>
                        <div class="col">
                            <div class="btn-group dropup">
                                <button type="button" class="p-2 btn btn-dark btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa-solid fa-ellipsis"></i>
                                </button>
                                <div class="dropdown-menu">
                                    <!-- Dropdown menu links -->
                                    <a class="dropdown-item" href="#">Редактировать</a>
                                    <a class="dropdown-item" href="{{ url_for('playlist.delete_playlist', playlist_id=playlist.id) }}">Удалить</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

webapp/templates/user/registration.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-4">
        <h1>{{ page_title }}</h2>
        <form action="{{ url_for('user.process_reg') }}" method="post">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.username.label }}<br>
                {{ form.username() }}
            </div>
            <div class="form-group">
                {{ form.email.label }}<br>
                {{ form.email() }}
            </div>
            <div class="form-group">
                {{ form.password.label }}<br>
                {{ form.password() }}
            </div>
            <div class="form-group">
                {{ form.password2.label }}<br>
                {{ form.password2() }}
            </div>
            {{ form.submit }}
        </form>
    </div>
</div>
{% endblock %}

webapp/templates/user/synchronization.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center mt-3 mb-3">AnySync</h3>
<h4 class="text-center">Для синхронизации выберите плейлисты.</h4>
<form action="/users/sync-playlist">
	<table class="table table-striped mt-5">
	<thead class="thead-dark">
			<tr>
				<th scope="col" class="text-center">#</th>
				<th scope="col">Название плейлиста</th>
				<th scope="col">Количество треков</th>
				<th scope="col">Автор</th>
			</tr>
	</thead>
		<tbody>
			{% for playlist in playlists %}
			<tr>
				<td scope="row">
					<div class="form-check text-center">
						<input name="playlist" class="form-check-input" type="checkbox" value="{{ playlist.id }}" id="{{ playlist.id }}">
					</div>
				</td>
				<td>
					<img src="{{ playlist.img_cover }}" alt="..." class="mr-3" width="40">
					<a href="{{ url_for('playlist.playlist', playlist_id=playlist.id) }}">{{ playlist.playlist_name }}</a>
				</td>
				<td>{{ playlist.count_tracks() }}</td>
				<td>{{ playlist.owner_name }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	<div class="row">
		<div class="col mb-3">
			<p>
				Сделать плейлист публичным?
			</p>
			<div class="custom-control custom-radio mb-3">
				<input type="radio" id="customRadio1" name="public_playlist" class="custom-control-input mr-3" value="True" required>
				<label class="custom-control-label" for="customRadio1">Да</label>
			</div>
			<div class="custom-control custom-radio">
				<input type="radio" id="customRadio2" name="public_playlist" class="custom-control-input mr-3" value="False" required>
				<label class="custom-control-label" for="customRadio2">Нет</label>
				<div class="invalid-feedback">Выберите Да или Нет.</div>
			</div>
		</div>
		<div class="col mb-3">
			<p>
				Выбранные плейлисты будут перенесены в 
				{% if music_service == 'Spotify' %}
				<i class="fa-brands fa-spotify"></i>
				{% elif music_service == 'Yandex Music' %}
				<i class="fa-brands fa-yandex"></i>
				{% endif %}
				{{ music_service }}.
			</p>
			<input type="radio" checked="checked" id="customRadio3" name="music_service" class="custom-control-input" value="{{ music_service }}" required>
		</div>
	</div>
	<div class="col mb-5">
		<button type="submit" class="btn btn-primary">Отправить</button>
	</div>
</form>
{% endblock %}

webapp/templates/user/unconfirmed.html
{% extends "base.html" %}

{% block content %}

<h1>Welcome!</h1>
<br>
<p>You have not confirmed your account. Please check your inbox (and your spam folder) - you should have received an email with a confirmation link.</p>
<p>Didn't get the email? <a href="/">Resend</a>.</p>

{% endblock %}

webapp/templates/user/yandexoauth.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-4">
		<h1>{{ page_title }}</h2>
		<form action="{{ url_for('user.yandex_login_process') }}" method="post">
			{{ form.hidden_tag() }}
			<div class="form-group">
				{{ form.email.label }}<br>
				{{ form.email() }}
			</div>
			<div class="form-group">
				{{ form.password.label }}<br>
				{{ form.password() }}
			</div>
			{{ form.submit }}
		</form>
	</div>
</div>
{% endblock %}