webapp/admin/views.py
"""
Admin views
"""
from flask import Blueprint, render_template

from webapp.playlist.models import Playlist
from webapp.user.decorators import admin_required
from webapp.user.models import User

blueprint = Blueprint("admin", __name__, url_prefix="/admin")


@blueprint.route("/")
@admin_required
def admin_index():
    """
    Admin index page

    Returns:
        HTML admin index page
    """
    title = "Админ панель"
    users = User.query.all()
    users_count = User.query.count()
    playlists_count = Playlist.query.count()

    return render_template(
        "admin/index.html",
        title=title,
        users=users,
        users_count=users_count,
        playlists_count=playlists_count,
    )

webapp/user/views.py
"""
Init user views
"""
from datetime import datetime

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
# from yandex_music import Client

from webapp.db import db
from webapp.playlist.models import Playlist
from webapp.spotify.spotify import spotify_auth, sync_to_spotify
from webapp.user.forms import LoginForm, RegistrationForm, YandexLoginForm
from webapp.user.models import User
from webapp.ya_music.token_ya import yandex_ouath


blueprint = Blueprint("user", __name__, url_prefix="/users")


@blueprint.route("/profile")
@login_required
def profile():
    """
    User profile page
    """
    title = "Мой AnySync"
    playlists = Playlist.query.filter(Playlist.user == current_user.id)
    return render_template("user/my_anysync.html", title=title, playlists=playlists)


@blueprint.route("/startspotoauth")
@login_required
def start_spot_oauth():
    """
    Getting an auth_url then redirect
    """
    auth_manager = spotify_auth()
    auth_url = auth_manager.get_authorize_url()
    print(auth_url)

    return redirect(auth_url)


@blueprint.route("/spotifyoauth")
@login_required
def spotifyoauth():
    """
    Getting spotify auth token
    """
    auth_manager = spotify_auth()
    print(request.args)
    auth_manager.get_access_token(request.args.get("code"))

    return redirect(url_for("user.synchronization", music_service="Spotify"))


@blueprint.route('/yandex-login-process', methods=["POST"])
@login_required
def yandex_login_process():
    """
    Yandex auth process page, validating form
    """
    form = YandexLoginForm()
    flash_message = "Неправильное имя пользователя или пароль"
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        auth_result, flash_message = yandex_ouath(email, password)
        if auth_result:
            flash(flash_message)
            return redirect(url_for("user.synchronization", music_service="Yandex Music"))
    flash(flash_message)

    return redirect(url_for("user.yandexoauth"))


@blueprint.route("/yandexoauth")
@login_required
def yandexoauth():
    """
    Check if the user already have a token, if not redirect to Yandex Auth
    """
    if current_user.yandex_token is None:
        title = 'Яндекс Авторизация'
        form = YandexLoginForm()
        return render_template(
            "user/yandexoauth.html",
            page_title=title,
            form=form,
        )
    return redirect(url_for("user.synchronization", music_service="Yandex Music"))


@blueprint.route("/sync-playlist")
@login_required
def sync_playlist():
    """
    Sync playlist in music service
    """
    playlist_ids = request.values.getlist("playlist")
    music_service = request.values.get("music_service")
    public_playlist = request.values.get("public_playlist") == "True"

    if music_service == "Spotify":
        auth_manager = spotify_auth()
        sync_to_spotify(
            playlist_ids=playlist_ids,
            public_playlist=public_playlist,
            auth_manager=auth_manager,
        )
    elif music_service == "Yandex Music":
        from webapp.tasks import new_playlist
        token = current_user.yandex_token
        # client = Client(token).init()
        new_playlist.delay(playlist_ids=playlist_ids, token=token)
    return redirect(url_for('user.profile'))


@blueprint.route("/synchronization/<music_service>")
@login_required
def synchronization(music_service):
    """
    Synchronization page with playlist checkboxes
    """
    title = "Синхронизация плейлистов"
    playlists = Playlist.query.filter(Playlist.user == current_user.id)

    return render_template(
        "user/synchronization.html",
        title=title,
        playlists=playlists,
        music_service=music_service,
    )


@blueprint.route("/login")
def login():
    """
    Login page
    """
    if current_user.is_authenticated:
        return redirect(url_for("index"))
    title = "Авторизация"
    login_form = LoginForm()

    return render_template("user/login.html", page_title=title, form=login_form)


@blueprint.route("/process-login", methods=["POST"])
def process_login():
    """
    Validatin login form
    """
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("Вы успешно вошли на сайт")
            return redirect(url_for("index"))
    flash("Неправильное имя пользователя или пароль")

    return redirect(url_for("user.login"))


@blueprint.route("/logout")
def logout():
    """
    Logout view
    """
    logout_user()
    flash("Вы успешно разлогинились")

    return redirect(url_for("index"))


@blueprint.route("/register")
def register():
    """
    Registration page
    """
    if current_user.is_authenticated:
        return redirect(url_for("index"))
    title = "Регистрация"
    form = RegistrationForm()

    return render_template("user/registration.html", page_title=title, form=form)


@blueprint.route("/process-reg", methods=["POST"])
def process_reg():
    """
    Validating registration form
    """
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(
            username=form.username.data,
            email=form.email.data,
            role="user",
            registration_date=datetime.today().strftime("%Y-%d-%m %H:%M:%S"),
        )
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash("Вы успешно зарегистрировались!")
        return redirect(url_for("user.login"))

    for field, errors in form.errors.items():
        for error in errors:
            flash(
                f'Ошибка в поле \
                "{getattr(form, field).label.text}": - {error}'
            )
    return redirect(url_for("user.register"))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<title>{{ page_title }}</title>
		<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
	</head>
	<body>
		{% include 'menu.html' %}
		<div class="container">
			<div class="col-4">
				{% with messages = get_flashed_messages() %}
					{% if messages %}
					<div class="alert alert-warning" role="alert">
						{% for message in messages %}
							{{ message }}<br>
						{% endfor %}
					</div>
					{% endif %}
				{% endwith %}
			</div>
			{% block content %}
			{% endblock %}
		</div>
		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
		<script src="https://kit.fontawesome.com/73f792baa6.js" crossorigin="anonymous"></script>
	</body>
</html>

webapp/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="col-md-8 mx-auto text-center">
    <h1 class="mt-5 mb-5">Синхронизируйте свои плейлисты в несколько кликов</h2>
    </div>
<hr>
<div class="col-md-8 mx-auto text-center">
    <h5 class="mb-3">
        AnySync предоставляет возможность синхронизировать и переносить ваши плейлисты из одного музыкального сервиса в другой.
    </h5>
    <div class="row">
        <div class="col">
            <a href="https://www.spotify.com/" class="text-success">
                <h5>
                    <i class="fa-brands fa-spotify pr-1"></i>Spotify
                </h5>
            </a>
        </div>
        <div class="col">
            <a href="https://music.yandex.ru/" class="text-warning">
                <h5>
                    <i class="fa-brands fa-yandex pr-1"></i>Yandex Music
                </h5>
            </a>
        </div>
    </div>
    <hr>
    <h5>
        Теперь вам не придётся делать это вручную, AnySync сделает это за вас, вам останется выбрать только сервис и плейлист.
    </h5>
    <hr>
    <h5>
        Интерфейс AnySync удобный и интуитивно понятный, всего в пару кликов вы можете добавить, а затем синхронизировать плейлисты.
    </h5>
</div>
{% endblock %}

webapp/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="col-4">
    <form action="{{ url_for('process_login') }}" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.username.label }}<br>
            {{ form.username() }}
        </div>
        <div class="form-group">
            {{ form.password.label }}<br>
            {{ form.password() }}
        </div>
        {{ form.submit }}
    </form>
</div>
{% endblock %}

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="/">AnySync</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item">
				<a class="nav-link" href="/">Главная</a>
			</li>
		</ul>
		<ul class="navbar-nav mr-right">
			{% if current_user.is_authenticated %}
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="margin: 7px;">
					Привет, {{ current_user.username }}
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{{ url_for('user.profile') }}">Мой AnySync</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="#">Настройки</a>
					</div>
				</li>
				{% if current_user.is_admin %}
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('admin.admin_index') }}">
							<button class="btn btn-outline-light my-2 my-sm-0" type="submit">Админка</button>
						</a>
					</li>
				{% endif %}
				<li class="nav-item">
					<a class="nav-link" href="{{ url_for('user.logout') }}">
						<button class="btn btn-outline-light my-2 my-sm-0" type="submit">Выйти</button>
					</a>
				</li>
			{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{{ url_for('user.login') }}">
						<button class="btn btn-outline-light my-2 my-sm-0" type="submit">Войти</button>
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ url_for('user.register') }}">
						<button class="btn btn-outline-light my-2 my-sm-0" type="submit">Регистрация</button>
					</a>
				</li>
			{% endif %}
		</ul>
	</div>
</nav>

webapp/templates/test.html
{% extends 'base.html' %}
{% block content %}
<div class="row mt-3">
	<div class="col">
		<form action="" method="post">
			{{ form.hidden_tag()}}
			<div class="form-group">
				{{ form.link.label }} {{ form.link() }}
			</div>
			<div>
				{{ form.submit }}
			</div>
		</form>
	</div>
	<div class="col">
		<p>Доступные музыкальные сервисы:</p>
		<div class="list-group">
			<a href="https://www.spotify.com/" class="list-group-item list-group-item-action">Spotify</a>
			<a href="https://music.yandex.ru/" class="list-group-item list-group-item-action">Yandex Music</a>
			<a href="https://music.apple.com/" class="list-group-item list-group-item-action disabled">В разработке Apple Music</a>
		</div>
	</div>
</div>
{% endblock %}