webapp/playlist/models.py
"""
Init playlist models
"""
from webapp.db import db


class Track(db.Model):
    """
    Track model
    """
    id = db.Column(db.Integer, primary_key=True)
    playlist = db.Column(db.Integer, db.ForeignKey("playlist.id"))
    artist = db.Column(db.String, nullable=False)
    track_name = db.Column(db.String, nullable=False)
    duration = db.Column(db.String, nullable=False)
    img_cover = db.Column(db.String, nullable=True)

    def __repr__(self):
        """
        Rerp of a Playlist model
        """
        return f"<Track {self.track_name} by {self.artist}>"


class Playlist(db.Model):
    """
    Playlist model
    """
    id = db.Column(db.Integer, primary_key=True)
    user = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=True)
    playlist_name = db.Column(db.String, nullable=False)
    owner_name = db.Column(db.String, nullable=False)
    last_update = db.Column(db.Date, nullable=True)
    description = db.Column(db.Text, nullable=True)
    img_cover = db.Column(db.String, nullable=True)
    kind = db.Column(db.String, nullable=True)

    def __repr__(self):
        """
        Rerp of a Playlist model
        """
        return f"<Playlist {self.playlist_name} {self.owner_name}>"

    def count_tracks(self):
        """
        Playlist's count tracks
        """
        return Track.query.filter(Track.playlist == self.id).count()

webapp/playlist/forms.py
"""
Init playlist forms
"""
from flask_wtf import FlaskForm
from wtforms import SubmitField, URLField
from wtforms.validators import URL, DataRequired


class PlaylistLinkForm(FlaskForm):
    """Init form for playlist lint process.

    Args:
        Ancestor class: FlaskForm
    """
    link = URLField(
        "Ссылка на плейлист",
        validators=[DataRequired(), URL()],
        render_kw={"class": "form-control"},
    )
    submit = SubmitField("Отправить", render_kw={"class": "btn btn-primary"})

webapp/playlist/__init__.py
"""
Init playlist
"""

webapp/playlist/views.py
"""
Playlist views
"""
from datetime import datetime
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import login_required

from webapp.db import db
from webapp.playlist.forms import PlaylistLinkForm
from webapp.playlist.models import Playlist, Track
from webapp.spotify.spotify import get_playlist_by_id
from webapp.ya_music.ya_music import get_playlist_ya

blueprint = Blueprint("playlist", __name__, url_prefix="/playlist")


@blueprint.route("/", methods=["GET", "POST"])
@login_required
def search_playlist_by_url():
    """View for search playlist by url

    Returns:
        HTML page with playlist-link form.
    """
    title = "AnySync"
    url_form = PlaylistLinkForm()

    return render_template("playlist/search_playlist_by_url.html", page_title=title, form=url_form)


@blueprint.route("/search-playlist-process", methods=["POST"])
@login_required
def search_playlist_process():
    """
    Search playlist process page, validating the form
    """
    url_form = PlaylistLinkForm()
    if url_form.validate_on_submit():
        if "spotify" in url_form.link.data:
            try:
                new_playlist = get_playlist_by_id(url_form.link.data)
                return redirect(url_for("playlist.playlist", playlist_id=new_playlist.id))
            except Exception:
                flash('Несуществующий плейлист в Spotify')
                return redirect(url_for("playlist.search_playlist_by_url"))
        if "yandex" in url_form.link.data:
            try:
                new_playlist = get_playlist_ya(url_form.link.data)
                return redirect(url_for("playlist.playlist", playlist_id=new_playlist.id))
            except Exception:
                flash('Несуществующий плейлист в Yandex Music')
                return redirect(url_for("playlist.search_playlist_by_url"))

        flash("Неправильная ссылка, попробуйте еще раз")
        return redirect(url_for("playlist.search_playlist_by_url"))

    flash("Ошибка при заполнении формы, попробуйте еще раз")
    return redirect(url_for("playlist.search_playlist_by_url"))


@blueprint.route("/playlists")
@login_required
def all_playlists():
    """View for all playlists

    Returns:
        HTML page with all users playlists.
    """
    title = "Список плейлистов"
    playlists = Playlist.query.all()

    return render_template(
        "playlist/playlists.html", page_title=title, playlists=playlists
    )


@blueprint.route("/playlist/<playlist_id>", methods=["GET", "POST"])
@login_required
def playlist(playlist_id):
    """View for playlist by id

    Returns:
        HTML page with tracks by playlist id.
    """
    title = "Треклист"
    current_playlist = Playlist.query.filter(Playlist.id == playlist_id).first()
    track_list = Track.query.filter(Track.playlist == playlist_id)

    return render_template(
        "playlist/playlist.html",
        page_title=title,
        track_list=track_list,
        current_playlist=current_playlist,
    )


@blueprint.route("/playlist_user/<user_id>", methods=["GET", "POST"])
@login_required
def playlist_user(user_id):
    """View for playlists by user id

    Returns:
        HTML page with playlists by user id
    """
    title = "Мои плейлисты"
    playlists = Playlist.query.filter(Playlist.user == user_id)
    return render_template(
        "playlist/playlist_user.html",
        page_title=title,
        playlists=playlists,
        user_id=user_id,
    )


@blueprint.route("/delete_playlist/<playlist_id>")
@login_required
def delete_playlist(playlist_id):
    """View for deleting playlist from the db

    Args:
        playlist_id: playlist id

    Returns:
        redirect to a user profile page
    """
    playlist_to_delete = Playlist.query.get(int(playlist_id))
    Track.query.filter(Track.playlist == int(playlist_id)).delete()
    db.session.delete(playlist_to_delete)
    db.session.commit()

    return redirect(url_for("user.profile"))


@blueprint.route("/delete_track_from_playlist/<track_id>")
@login_required
def delete_track(track_id):
    """View for deleting playlist from the db

    Args:
        track_id: track_id id

    Returns:
        redirect to the playlist page
    """
    track_to_delete = Track.query.get(int(track_id))
    playlist_id = track_to_delete.playlist
    playlist_to_update = Playlist.query.get(track_to_delete.playlist)
    playlist_to_update.last_update = datetime.today()

    db.session.delete(track_to_delete)
    db.session.commit()

    return redirect(url_for("playlist.playlist", playlist_id=playlist_id))

webapp/templates/playlist/playlist.html
{% extends 'base.html' %}

{% block content %}
<h2 class="mt-3">{{ page_title }}: {{ current_playlist.playlist_name }}</h2>
<table class="table table-striped mt-5">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название трека</th>
            <th scope="col">Исполнитель</th>
            <th scope="col">Длительность</th>
            {% if current_playlist.user == current_user.id %}
            <th scope="col"><i class="fa-solid fa-trash"></i></th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for track in track_list %}
        <tr>
            <td scope="row">{{ loop.index }}</td>
            <td>
                <img src="{{ track.img_cover }}" alt="..." class="mr-3" width="40">
                {{ track.track_name }}
            </td>
            <td>{{ track.artist }}</td>
            <td>{{ track.duration }}</td>
            {% if current_playlist.user == current_user.id %}
            <th scope="col"><a href="{{ url_for('playlist.delete_track', track_id=track.id) }}" style="text-decoration: none; color: #000;"><i class="fa-solid fa-trash"></i></a></th>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

webapp/templates/playlist/playlist_user.html
{% extends 'base.html' %}

{% block content %}
{% if playlists.count() > 0 %}
<h2 class="mt-3">Мои плейлисты</h2>
<table class="table table-striped mt-5">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название плейлиста</th> 
            <th scope="col">Количество треков</th>
            <th scope="col">Автор</th>
        </tr>
    </thead>
    <tbody>
        {% for playlist in playlists %}
        <tr>
            <th scope="row">{{ loop.index }}</th>
            <td>
                <img src="{{ playlist.img_cover }}" alt="..." class="mr-3" width="40">
                <a href="{{ url_for('playlist.playlist', playlist_id=playlist.id) }}">{{ playlist.playlist_name }}</a>
            </td>
            <td>{{ playlist.count_tracks() }}</td>
            <td>{{ playlist.owner_name }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<h4>Нет плейлистов</h4>
{% endif %}
{% endblock %}

webapp/templates/playlist/playlists.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-striped mt-5">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название плейлиста</th>
            <th scope="col">Количество треков</th>
            <th scope="col">Автор</th>
        </tr>
    </thead>
    <tbody>
        {% for playlist in playlists %}
        <tr>
            <td scope="row">{{ loop.index }}</td>
            <td>
                <img src="{{ playlist.img_cover }}" alt="..." class="mr-3" width="40">
                <a href="{{ url_for('playlist.playlist', playlist_id=playlist.id) }}">{{ playlist.playlist_name }}</a>
            </td>
            <td>{{ playlist.count_tracks() }}</td>
            <td>{{ playlist.owner_name }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

webapp/templates/playlist/search_playlist_by_url.html
{% extends 'base.html' %}

{% block content %}
<div class="row mt-5">
	<div class="col">
		<h4 class="pb-3 text-center">Создание плейлиста</h4>
		<p class="text-center">Для добавления плейлиста укажите ссылку.</p>
		<form class="pt-3" action="{{ url_for('playlist.search_playlist_process') }}" method="post">
			{{ form.hidden_tag() }}
			<div class="form-group">
				{{ form.link.label }} {{ form.link() }}
			</div>
			<div>
				{{ form.submit }}
			</div>
		</form>
	</div>
	<div class="col-5 text-center mx-auto">
		<div class="list-group list-group-flush">
			<h5 class="list-group-item">Доступные музыкальные сервисы:</h5>
			<a href="https://www.spotify.com/" class="list-group-item list-group-item-action">
				<i class="fa-brands fa-spotify pr-3"></i>Spotify
			</a>
			<a href="https://music.yandex.ru/" class="list-group-item list-group-item-action">
				<i class="fa-brands fa-yandex pr-3"></i>Yandex Music
			</a>
			<span class="list-group-item list-group-item-action disabled">
				В разработке:
			</span>
			<a href="https://music.apple.com/" class="list-group-item list-group-item-action disabled">
				<i class="fa-brands fa-itunes pr-3"></i>Apple Music
			</a>
		</div>
	</div>
</div>
{% endblock %}

webapp/templates/playlist/test.html
{% extends 'base.html' %}

{% block content %}
<div class="row mt-5">
	<div class="col">
		<h4 class="pb-3 text-center">Создание плейлиста</h4>
		<p class="text-center">Для добавления плейлиста укажите ссылку.</p>
		<form class="pt-3" action="" method="post">
			{{ form.hidden_tag() }}
			<div class="form-group">
				{{ form.link.label }} {{ form.link() }}
			</div>
			<div>
				{{ form.submit }}
			</div>
		</form>
	</div>
	<div class="col-5 text-center mx-auto">
		<div class="list-group list-group-flush">
			<h5 class="list-group-item">Доступные музыкальные сервисы:</h5>
			<a href="https://www.spotify.com/" class="list-group-item list-group-item-action">
				<i class="fa-brands fa-spotify pr-3"></i>Spotify
			</a>
			<a href="https://music.yandex.ru/" class="list-group-item list-group-item-action">
				<i class="fa-brands fa-yandex pr-3"></i>Yandex Music
			</a>
			<span class="list-group-item list-group-item-action disabled">
				В разработке:
			</span>
			<a href="https://music.apple.com/" class="list-group-item list-group-item-action disabled">
				<i class="fa-brands fa-itunes pr-3"></i>Apple Music
			</a>
		</div>
	</div>
</div>
{% endblock %}